name: Flutter Debug Build

on:
  push:
    branches:
      - develop

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@4.6.2
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk